// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9zbbwSZBUaeQviyP0d-SPLbEYbc_DcmI',
    appId: '1:1032417254827:web:ff402750f4a18f104406ee',
    messagingSenderId: '1032417254827',
    projectId: 'rate-my-poo',
    authDomain: 'rate-my-poo.firebaseapp.com',
    storageBucket: 'rate-my-poo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQwduOHxjDcr1Pde-y--6exvBL0ScHit0',
    appId: '1:1032417254827:android:71f5ccc9c4865cd14406ee',
    messagingSenderId: '1032417254827',
    projectId: 'rate-my-poo',
    storageBucket: 'rate-my-poo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7FjpuBJWoZQPQH4zgaVKUna4sDayfFPQ',
    appId: '1:1032417254827:ios:6b69ac4ce5802deb4406ee',
    messagingSenderId: '1032417254827',
    projectId: 'rate-my-poo',
    storageBucket: 'rate-my-poo.firebasestorage.app',
    iosBundleId: 'com.example.ratemypoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7FjpuBJWoZQPQH4zgaVKUna4sDayfFPQ',
    appId: '1:1032417254827:ios:6b69ac4ce5802deb4406ee',
    messagingSenderId: '1032417254827',
    projectId: 'rate-my-poo',
    storageBucket: 'rate-my-poo.firebasestorage.app',
    iosBundleId: 'com.example.ratemypoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9zbbwSZBUaeQviyP0d-SPLbEYbc_DcmI',
    appId: '1:1032417254827:web:d38c97392fcd8c534406ee',
    messagingSenderId: '1032417254827',
    projectId: 'rate-my-poo',
    authDomain: 'rate-my-poo.firebaseapp.com',
    storageBucket: 'rate-my-poo.firebasestorage.app',
  );
}
